@Restaurants.API_HostAddress = http://localhost:5209


@RestaurantsAPI_HostAddress = http://localhost:5209

@token =CfDJ8BnLFYmBvoxJvOw16aNbyBdac3PdIlSQV8lRT4l2L8Zb45-xwr_dKXEIA6ri5pQHUwztdXfK0XMzrlMZxp6HAun2Pz-YkYAskyJZXC0EdSs906SCHvevmGnfvILjyKASh8m01q0RWh1P5oPvCxo26MRUMeIBSzGoRVW-m3JTzO4CTFgAfdstTmNreiJSXoHMvJf53T4hmjEHj8NB388z-H8mUwtQ85OSDd9rvD07dej0OSNE4pPvbjoxLoZsYg403l-HZxFSUa_46yoJ3gMkVEtiCuNFbqVAQ6e2GSwYHiwyS3jqZUjaoefVxrbi4WyHuCImY6I_jpLruxNrulK_Us1DSCPvY-hcY3h1WVmAzUEADk2lS10n8eGehCtGJNdcFY2KuOtFDs7RCn2XcgqXvTL8fRNj-4AyWMfM3N0Ry9nykNc43Qp5GjWtQVXfPyc8ZILV3P0H-wmBaHgIkaOo6R1b-j4dbzmbYF_t1uDMwhYDw7M7_gnVT7Dg0fildHj3tRWTCHqwkqvlcEv0jVHQnHptYRMUsVs2y-2N0Ycp39jxsuv4-9TrezjVba5Bb_JwQMteBXVBPG6B_FII-Zi7QH3eYjxZt1UeG6pGCeiCOdmhRdOgn3pXnv0YElVqRU7rMW3CQGEF7f7TD03eF4ZGLjtHpfwn3zA7TkBsEhU2txvttC-SMqZF-i7sfzREr2-NtaRLad8A9nn30l8qM6b--n4

GET {{RestaurantsAPI_HostAddress}}/weatherforecast?count={{count}}&minTemp={{minTemp}}&maxTemp={{maxTemp}}
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants

Authorization: Bearer {{token}}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/1

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/{id}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/{id}

###


@RestaurantsAPI_HostAddress = http://localhost:5209
POST http://localhost:5209/api/restaurants
Content-Type: application/json

{ 
"Name": "Pizza 3izzedine",
"Description": "A culinary experience like no oth",
"Category": "Indain",
"HasDelivery": true,
"ContactEmail":
"info@gourmetdelights.com",
"ContactNumber": "555-123-4567",
"City": "Metropolis",
"Street": "456 Gourmet Avenue",
"PostalCode": "54-321"
}

###

@RestaurantsAPI_HostAddress = http://localhost:5209
DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/3

###

@RestaurantsAPI_HostAddress = http://localhost:5209
PATCH http://localhost:5209/api/restaurants/2
Content-Type: application/json

{
  "Name":"Mac Donanld",
   "description": "McDonald's restaurants mainly serve hamburgers, cheeseburgers, chicken nuggets, burgers, french fries, breakfast items, soft drinks, milk shakes and desserts. They also have options such as salads, apples, milk, McDonald's Popular Picks"
}

###
@RestaurantsAPI_HostAddress = http://localhost:5209
GET {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes

###
@RestaurantsAPI_HostAddress = http://localhost:5209
POST {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "lablabi",
  "description": "lablabi",
  "price": 15,
  "kiloCalories": 2000,
  "restaurantId": 2
}

###

POST {{RestaurantsAPI_HostAddress}}/register
Content-Type: application/json

{
    "email": "leithgharbi@yahoo.fr",
    "password" :"Azertyuiop1$"
}

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "leithgharbi@yahoo.fr",
    "password" :"Azertyuiop1$"
}
