@Restaurants.API_HostAddress = http://localhost:5209


@RestaurantsAPI_HostAddress = http://localhost:5209

@token = CfDJ8BnLFYmBvoxJvOw16aNbyBcZ7IGvzXzKL_2GG5sWbtTmW39L48WVl9aSBRSsEF2c_EdpL43CbOkJf0gyW_QaSuGi7dZeOz4105UsZ3vPkyjKY22EcAphGMVDrEqOG0gCeH9wvRsjzkHYYi89C2XgRhk528LLVG3BaAlIht3O_qvZodQqOcUtdBdltArVM-p4wYZh9UGaTOhjAeaXywnR-T-r4ESkdD01PSVjIqt9KNIakMQGeY6Q56Qu9RAUhfSRf2yauq3fNxk23n3HhD_TSRAGTWSfomCzaK1CjV1H4tu-Sj5zsiAy8K7UHmR2AHxivnBKFTP6VESokg3B8zCYZcr7pNMpXXoZbw-Hle6rixVlPI2a4vobtTe36iZGFjGhb2BORDvhsw31wAuAz-SbqRqvJbwPKUxI2r0PnQora5ycjQRf0JbtooAOcdFCGP5HIC49dicABNie7uvHvPezuf2Dpb9r9vMSlLQYOuD8jNI5yefBpDkF1h989yxByUF3kDeSF-UVH1n5iv7uBjk7jceR-LeG9nQti9F_FqsWBnWGaMTn0eyvt2P2YfyESSxskeafqNpNq7yjmP9of2LmDA6MJfNBgt_nhiI139AlPfoNGwKq9Rqt-SrvYuSXTqm8R21qQ2sejd3rcDcQekJcGowKp4ca2jREAe5zktuqF3ahGFOiRJ99PjT_i4Y5bNVsGLA_EaB9a1w0u1uwNYuDNiFNcKlfmABvv7YqmqSA76fN4NCOR4Dj2ZF4L7_F7X-8cK8VOoRoR3Rj_AapodBrh1bHRYMf_yvLfKhVa9xT-2lg
GET {{RestaurantsAPI_HostAddress}}/weatherforecast?count={{count}}&minTemp={{minTemp}}&maxTemp={{maxTemp}}
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/1

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/{id}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/{id}

###


@RestaurantsAPI_HostAddress = http://localhost:5209
POST http://localhost:5209/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
"Name": "mlewi janoub ",
"Description": "A culinary experience like no oth",
"Category": "Indain",
"HasDelivery": true,
"ContactEmail":
"info@gourmetdelights.com",
"ContactNumber": "555-123-4567",
"City": "Metropolis",
"Street": "456 Gourmet Avenue",
"PostalCode": "54-321"
}

###

@RestaurantsAPI_HostAddress = http://localhost:5209
DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/3

###

@RestaurantsAPI_HostAddress = http://localhost:5209
PATCH http://localhost:5209/api/restaurants/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Mac Donanld",
   "description": "McDonald's restaurants mainly serve hamburgers, cheeseburgers, chicken nuggets, burgers, french fries, breakfast items, soft drinks, milk shakes and desserts. They also have options such as salads, apples, milk, McDonald's Popular Picks"
}

###
@RestaurantsAPI_HostAddress = http://localhost:5209
GET {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes

###
@RestaurantsAPI_HostAddress = http://localhost:5209
POST {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "lablabi",
  "description": "lablabi",
  "price": 15,
  "kiloCalories": 2000,
  "restaurantId": 2
}

###

POST {{RestaurantsAPI_HostAddress}}/register
Content-Type: application/json

{
    "email": "leithgharbi@yahoo.fr",
    "password" :"Azertyuiop1$"
}

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password" :"Azertyuiop$1"
}


###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
   "email": "leithgharbi@yahoo.fr",
    "password" :"Azertyuiop1$"
}
