@Restaurants.API_HostAddress = http://localhost:5209


@RestaurantsAPI_HostAddress = http://localhost:5209

@token = CfDJ8BnLFYmBvoxJvOw16aNbyBeW0AasvuACypo4tb0D8j0oOGeW2ojkDDzL-ouXVO0wNZbQBzHMYSNbg5-gT4r0nDngSddz6CDmTDHED6odGfkQUzleUcuY7UQ8zq7anLFTt27alLzqJT-AqHqDYXCA9DKLcqEaqTGv9tUYyBKR28BxDAzsJUZRdNmF4d9VByg7dtKoKeXzbHhtl3d_WxLcWdAQ8bogWO2m4MqDxRaAzGiOSKfWjX2VFW8WyjPsUwULBEkfIn5gBU5K8nwLrPT8RqcBaSDC0RHSGAOYvKiVf3DAsOIANcZZ0ig9oBnJB_huJVsMJuvuLt4t5qqcWtrwIe1saAoLMR-43WEk1ygW7VcFgyBgjrjVslm-injLLjhHS26O7aBiPXaml-CB6Q8vI2hyUrCgEcnYq8sYadBKO2InwMIAXq9e69zIurjAfPZq7EiCZqVKOLFckPfLM_RPcqO9EL3QlAWhU_U6ToZ-qBtEPQOGOuwGWenmDwrMUxkwcAMW011K5r69VtrmBenQKVEc5pdZY9P5IY4KQMUoGyorlHpZS3oJ2Cem3D7g9ImejpHC2tNrr8b126UF2quBfRuO7Gi7vbxDT0YsxJB3QnpIvsXqWbRutQLkiDaXu_Xp_Q2FhrOpLy4IQjZWF7aLBgA1_nLzLIN8jtU180xTup9GUNK-BT1X2uFz6yrUh2ged6UCJ0JxflLH3OzYj47XPitaQJshaNF_6c36w_jFRlJwGEf8n65pDCceYWjXCKKN2rDjv0JtmrZWYTb9KWgP6H3DyERMtg4xOJ-cP03n_Nyb
GET {{RestaurantsAPI_HostAddress}}/weatherforecast?count={{count}}&minTemp={{minTemp}}&maxTemp={{maxTemp}}
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/1

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/{id}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/{id}

###


@RestaurantsAPI_HostAddress = http://localhost:5209
POST http://localhost:5209/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
"Name": "mlewi janoub ",
"Description": "A culinary experience like no oth",
"Category": "Indain",
"HasDelivery": true,
"ContactEmail":
"info@gourmetdelights.com",
"ContactNumber": "555-123-4567",
"City": "Metropolis",
"Street": "456 Gourmet Avenue",
"PostalCode": "54-321"
}

###

@RestaurantsAPI_HostAddress = http://localhost:5209
DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/3

###

@RestaurantsAPI_HostAddress = http://localhost:5209
PATCH http://localhost:5209/api/restaurants/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Mac Donanld",
   "description": "McDonald's restaurants mainly serve hamburgers, cheeseburgers, chicken nuggets, burgers, french fries, breakfast items, soft drinks, milk shakes and desserts. They also have options such as salads, apples, milk, McDonald's Popular Picks"
}

###
@RestaurantsAPI_HostAddress = http://localhost:5209
GET {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes

###
@RestaurantsAPI_HostAddress = http://localhost:5209
POST {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "lablabi",
  "description": "lablabi",
  "price": 15,
  "kiloCalories": 2000,
  "restaurantId": 2
}

###

POST {{RestaurantsAPI_HostAddress}}/register
Content-Type: application/json

{
    "email": "leithgharbi@yahoo.fr",
    "password" :"Azertyuiop1$"
}

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password" :"Azertyuiop$1"
}


###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
   "email": "leithgharbi@yahoo.fr",
    "password" :"Azertyuiop1$"
}
